name: Style enforcer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: cs2pr, phpcs

      - name: Run phpcs
        run: phpcs -q --report=checkstyle app | cs2pr
